name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ sercerts.DOCKER_USERNAME }}
          password: ${{ sercerts.DOCKER_PASSWORD }}
      
      - name: Build and push
        uses: docker/build-push-actions@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/jason-docker-app:latest
      
      - name: Deploy to Swarm
        run: |
          echo "Deploying to Swarm...."
          # Optioneel: SHH naar jou server
          # ssh user@server "docker stack deploy -c docker-compose.yml mijn-mijn-cluster"
          

